# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/blocks/network_structure.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"src/blocks/network_structure.proto\x12\x06NBlock\")\n\x08TNetwork\x12\x1d\n\x05\x62lock\x18\x01 \x03(\x0b\x32\x0e.NBlock.TBlock\"\x82\x01\n\x06TBlock\x12.\n\x0b\x42lockHeader\x18\x01 \x01(\x0b\x32\x14.NBlock.TBlockHeaderH\x00\x88\x01\x01\x12*\n\tBlockData\x18\x02 \x01(\x0b\x32\x12.NBlock.TBlockDataH\x01\x88\x01\x01\x42\x0e\n\x0c_BlockHeaderB\x0c\n\n_BlockData\"\xe2\x01\n\x0cTBlockHeader\x12\x16\n\tBlockSize\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12 \n\x13PrevBlockHeaderHash\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x1b\n\x0eMerkleTreeHash\x18\x03 \x01(\x0cH\x02\x88\x01\x01\x12\x16\n\tTimestamp\x18\x04 \x01(\x03H\x03\x88\x01\x01\x12\x12\n\x05Nonce\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\x0c\n\n_BlockSizeB\x16\n\x14_PrevBlockHeaderHashB\x11\n\x0f_MerkleTreeHashB\x0c\n\n_TimestampB\x08\n\x06_Nonce\"!\n\nTBlockData\x12\x13\n\x0bTransaction\x18\x01 \x03(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.blocks.network_structure_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TNETWORK']._serialized_start=46
  _globals['_TNETWORK']._serialized_end=87
  _globals['_TBLOCK']._serialized_start=90
  _globals['_TBLOCK']._serialized_end=220
  _globals['_TBLOCKHEADER']._serialized_start=223
  _globals['_TBLOCKHEADER']._serialized_end=449
  _globals['_TBLOCKDATA']._serialized_start=451
  _globals['_TBLOCKDATA']._serialized_end=484
# @@protoc_insertion_point(module_scope)
